name: linkable_example
description: linkable example

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  linkable:
    path: ..

flutter:
  uses-material-design: true
